---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-production
  namespace: flux-system
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: devops-toolkit
  interval: 30s
  targetNamespace: devops-toolkit-production
  values:
    image:
      tag: 2.9.18
    ingress:
      host: staging.devops-toolkit.apps.okd.ag04.io

